name: Build and Release LavenderHook

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read Version File
        id: get_version
        run: |
          $ver = (Get-Content Version).Trim()
          echo "VERSION=$ver" >> $env:GITHUB_OUTPUT
        shell: powershell

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build Projects
        run: |
          cmake -B build-hook -S LavenderHook -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build build-hook

      - name: Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "LavenderHook ${{ steps.get_version.outputs.VERSION }}"
          body: "Automated build of the latest version."
          files: |
            build-hook/LavenderHook.dll
          make_latest: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}